### ISSUE TITLE
Re-write it in Rust

### ISSUE THREAD

**Issue by justinmoon** [justinmoon/minimint_helper#3]
Axum + Askama likely wouldn't require any changes to jinja templates. This is what I'm doing for [setup UI](https://github.com/fedimint/fedimint/pull/496) and it's worked nicely so far.

**Comment by elsirion** [comment]
Did you RIIR already? Otherwise why close? :pleading_face:

**Comment by justinmoon** [comment]
No. Just not productive to think about this right now I think ...
